version: '3'

services:
    redis-server:
        image: 'redis'
    python-app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        volumes:
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - .:/app
        command: ["python", "./test.py"]